### PR TITLE
MAINT: import from collections.abc

### PR DESCRIPTION
**Pull request by andyfaff**
In Python 3.7 importing `from collections` is deprecated and raises a `DeprecationWarning`. In Python 3.8 (scheduled for release in mid October) it will raise an Error. This PR fixes the import. Hopefully a release of pymc3 and theano can be done before then, otherwise the packages won't work in Python 3.8.

### CODE REVIEW

**Comment by andyfaff** [comment]
Note that this change is not back compatible to Python 2.7. If that's still required then some more modifications are required.

**Comment by twiecki** [comment]
```
    from collections.abc import defaultdict, Iterable
E   ImportError: cannot import name 'defaultdict'
```

**Comment by andyfaff** [comment]
Oops.

**Comment by twiecki** [comment]
Thanks!
