### ISSUE TITLE
ImportError: cannot import name IntEnum

### ISSUE THREAD

**Issue by qingkaikong** [pymc-devs/pymc#853]
Hi, 

I am trying to use pymc3, but I keep getting the following error, even after I reinstall pymc3. Could you help me please. Thanks. 

PS: I am working on a MacBook Pro with OS version 10.10.5. 

---

ImportError                               Traceback (most recent call last)
<ipython-input-7-582c90a634a6> in <module>()
----> 1 from pymc3 import Model, Normal, HalfNormal

/Users/qingkaikong/blog/07_regression/venv/lib/python2.7/site-packages/pymc3/**init**.py in <module>()
      6 
      7 from .stats import *
----> 8 from .sampling import *
      9 from .interactive_sampling import *
     10 from .step_methods import *

/Users/qingkaikong/blog/07_regression/venv/lib/python2.7/site-packages/pymc3/sampling.py in <module>()
      5 from time import time
      6 from .core import *
----> 7 from .step_methods import *
      8 from .progressbar import progress_bar
      9 from numpy.random import seed

/Users/qingkaikong/blog/07_regression/venv/lib/python2.7/site-packages/pymc3/step_methods/**init**.py in <module>()
      1 from .compound import *
----> 2 from .hmc import *
      3 from .metropolis import *
      4 from .gibbs import *
      5 from .slicer import *

/Users/qingkaikong/blog/07_regression/venv/lib/python2.7/site-packages/pymc3/step_methods/hmc.py in <module>()
      6 from numpy import floor
      7 from .quadpotential import *
----> 8 from .arraystep import *
      9 from ..core import *
     10 from ..tuning import guess_scaling

/Users/qingkaikong/blog/07_regression/venv/lib/python2.7/site-packages/pymc3/step_methods/arraystep.py in <module>()
      6 from numpy.random import uniform
      7 from numpy import log, isfinite
----> 8 from enum import IntEnum, unique
      9 
     10 **all** = ['ArrayStep', 'ArrayStepShared', 'metrop_select', 'SamplerHist',

ImportError: cannot import name IntEnum

**Comment by fonnesbeck** [comment]
This should be fixed by #852. Try building from master, and reopen this if the problem persists.
