### PR TITLE
fix: restore blackjax>=1.6 compatibility for nuts_sampler="blackjax"

### LINKED ISSUE #8367: BUG: `pm.sample(nuts_sampler="blackjax")` fails during warmup with every blackjax >= 1.6
### Describe the issue:

`pm.sample(nuts_sampler="blackjax")` fails during warmup with every blackjax >= 1.6, in all configurations, on all pymc versions (verified on 5.27.1 and 6.1.0).

Root cause: blackjax 1.6 removed the `progress_bar` parameter from `blackjax.window_adaptation` (progress bars moved to a context manager, `with blackjax.progress_bar(): warmup.run(...)`), and `window_adaptation` now forwards unknown `**extra_parameters` into the NUTS kernel. pymc unconditionally injects `progress_bar` into the sampler kwargs (`nuts_kwargs["progress_bar"] = progressbar`, `pymc/sampling/jax.py:359` in 6.1.0) and `_blackjax_inference_loop` only pops it *after* `blackjax.window_adaptation(**adaptation_kwargs)` has already been called (`pymc/sampling/jax.py:277` vs the `window_adaptation` call above it). The stale kwarg therefore reaches the blackjax NUTS kernel and raises during the first adaptation step.

A fix would be to pop `progress_bar` from `adaptation_kwargs` before calling `window_adaptation` and, for blackjax >= 1.6, use the new context-manager API (or drop the flag).

### Reproduceable code example:

```python
# pip install "pymc==6.1.0" "blackjax==1.6"  (also fails with pymc 5.27.1 + blackjax 1.6)
import numpy as np
import pymc as pm

with pm.Model():
    x = pm.Normal("x", 0.0, 1.0)
    pm.Normal("obs", x, 1.0, observed=np.array([0.3, -0.1, 0.5]))
    idata = pm.sample(
        draws=50, tune=50, chains=1,
        nuts_sampler="blackjax",
        progressbar=False,
    )
```

### Error message:

```shell
TypeError: build_kernel.<locals>.kernel() got an unexpected keyword argument 'progress_bar'


(raised from `blackjax/adaptation/window_adaptation.py` during `adapt.run`, wrapped by JAX tracing frames)
```

### PyMC version information:

pymc 5.27.1 and 6.1.0, blackjax 1.6, jax 0.10.x, Python 3.12, macOS (arm64) and Linux. Works with blackjax <= 1.5 (whose `window_adaptation` still accepted `progress_bar`).

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by laishettikarthik-tech**
blackjax 1.6 removed the progress_bar parameter from window_adaptation
(unknown kwargs now forward into the NUTS kernel and raise TypeError)
and replaced the progress_bar module (gen_scan_fn helper) with a
context-manager function.

- Pop progress_bar from adaptation_kwargs before calling
  window_adaptation, not after
- Dispatch on hasattr(blackjax.progress_bar, "gen_scan_fn") to support
  both the old module-based API and the new context-manager API

Closes #8367

### CODE REVIEW

**Comment by laishettikarthik-tech** [comment]
pre-commit.ci autofix

File: pymc/sampling/jax.py [hunk 1]
```diff
@@ -274,12 +280,34 @@ def _one_step(state, xs):
...
+    if hasattr(blackjax.progress_bar, "gen_scan_fn"):
+        # blackjax < 1.6: progress_bar is a module exposing gen_scan_fn,
+        # which wraps jax.lax.scan directly.
+        scan_fn = blackjax.progress_bar.gen_scan_fn(draws, progress_bar)
+        _, (samples, stats) = scan_fn(_one_step, last_state, (jnp.arange(draws), keys))
+    elif progress_bar:
+        # blackjax >= 1.6: progress_bar is a context manager that
+        # monkeypatches jax.lax.scan for its duration instead.
+        with blackjax.progress_bar(label="NUTS"):
+            _, (samples, stats) = jax.lax.scan(_one_step, last_state, (jnp.arange(draws), keys))
```
Comment (notluquis) [inline pymc/sampling/jax.py:300]: On blackjax >= 1.6 this context manager is powered by `jaxtap`, shipped as `blackjax[progress]`. On a plain `blackjax==1.6.2` install it raises:

```
ImportError: blackjax.progress_bar requires the 'progress' optional extra.
Install it with:  pip install 'blackjax[progress]'
```

So `test_sample_blackjax_nuts_progressbar_true` will fail on any CI image that installs blackjax without the extra, and a user passing `progressbar=True` trades a `TypeError` for an `ImportError`. A progress bar aborting a sampling run seems worse than losing the bar, so a fallback may be preferable to adding the extra as a test dependency (`warnings` is already imported at line 17):

```suggestion
    elif progress_bar:
        try:
            with blackjax.progress_bar(label="NUTS"):
                _, (samples, stats) = jax.lax.scan(_one_step, last_state, (jnp.arange(draws), keys))
        except ImportError:
            warnings.warn(
                "blackjax progress bar needs the 'progress' extra "
                "(pip install 'blackjax[progress]'); sampling without it.",
                UserWarning,
                stacklevel=2,
            )
            _, (samples, stats) = jax.lax.scan(_one_step, last_state, (jnp.arange(draws), keys))
```

File: pymc/sampling/jax.py [hunk 2]
```diff
@@ -274,12 +280,34 @@ def _one_step(state, xs):
...
+    else:
+        _, (samples, stats) = jax.lax.scan(_one_step, last_state, (jnp.arange(draws), keys))
```
Comment (notluquis) [inline pymc/sampling/jax.py]: This block repeats lines 283-295 verbatim and sits after the `return samples, stats` above it, so it is unreachable. Looks like a rebase artefact. It also accounts for the Codecov number — 55.6% patch coverage is roughly what you get when half the added lines cannot execute.

Deleting the added copy leaves the original `return samples, stats` below it, so the diff does not touch any pre-existing line.

```suggestion
```

**Review by notluquis — COMMENTED** [review]
Confirming the reproduction on a configuration not listed in #8367: **blackjax 1.6.2, pymc 6.1.0, jax 0.10.2, Python 3.13, macOS arm64**. The ordering bug is also present in the released **6.2.0** source, not only on `main`, so upgrading is not a workaround.

Applied this branch locally with the two changes suggested below. The issue's own reproduction then runs on both paths:

```
progressbar=False  ->  OK, posterior shape (1, 50), mean 0.1311
progressbar=True   ->  OK, warns about the missing extra and samples without the bar
```

The `hasattr(blackjax.progress_bar, "gen_scan_fn")` dispatch checks out: on 1.6.2 `blackjax.progress_bar` is a function rather than a module, `hasattr(..., "gen_scan_fn")` is `False`, and its signature is `(label='BlackJAX', print_rate=None, output_file=None)`, so `label="NUTS"` is valid.

---

Separate thought, out of scope for this fix. The reason this surfaced as `TypeError: build_kernel.<locals>.kernel() got an unexpected keyword argument` — naming a function nobody called, from inside JAX tracing — is that `window_adaptation` forwards unknown `**extra_parameters` straight through to the algorithm. Filtering against the real signature would turn any future stale kwarg into an error at its origin:

```python
accepted = inspect.signature(blackjax.window_adaptation).parameters
unknown = set(adaptation_kwargs) - set(accepted)
if unknown:
    raise TypeError(f"blackjax.window_adaptation does not accept {sorted(unknown)}")
```

A test for `progress_bar` specifically would not catch the next blackjax API change; this would.

**Comment by laishettikarthik-tech** [comment]
The tests / all_tests failure is unrelated to this PR — it's test_mvstudentt[NUMBA] in test_random_alternative_backends.py, a numerical tolerance mismatch in the Numba multivariate Student-T sampler, nothing to do with jax.py or blackjax. All 133 other tests passed, including the three TestBlackjaxProgressBarCompat tests. Ran the blackjax-specific tests locally too (see earlier comment) — all pass cleanly.

Given it's unrelated, might this need a rerun, or is test_mvstudentt[NUMBA] a known flake?

File: tests/sampling/test_jax.py [hunk 3]
```diff
@@ -502,3 +502,79 @@ def test_convergence_warnings(caplog, nuts_sampler):
...
+            )
+        assert idata.posterior["x"].shape == (1, 10)
+
+    def test_progress_bar_popped_before_window_adaptation(self):
+        # Directly asserts the ordering fix: progress_bar must never reach
+        # blackjax.window_adaptation's kwargs, regardless of blackjax
+        # version/API shape.
+        import blackjax
+
+        from pymc.sampling.jax import _blackjax_inference_loop
```
Comment (ricardoV94) [inline tests/sampling/test_jax.py]: check if local imports can be made global
