### ISSUE TITLE
Subclassing pm.Model doesn't work on PyMC3 3.8

### ISSUE THREAD

**Issue by fbartolic** [pymc-devs/pymc#3727]
Since I upgraded to  PyMC3 3.8 I'm getting the `AttributeError: module '__main__' has no attribute 'Model'` error when subclassing `pm.Model()`. 

Here's a minimal example which reproduces the issue:

```python
import pymc3 as pm


class CustomModel(pm.Model):
    def __init__(self):
        super().__init__()
        self.x = pm.Normal("x", 0.0, 1.0)


model = CustomModel()

```
Error:
```python
Traceback (most recent call last):
  File "test_bug.py", line 10, in <module>
    model = CustomModel()
  File "/Users/fb90/anaconda3/envs/pymc3/lib/python3.7/site-packages/pymc3/model.py", line 274, in __call__
    instance = cls.__new__(cls, *args, **kwargs)
  File "/Users/fb90/anaconda3/envs/pymc3/lib/python3.7/site-packages/pymc3/model.py", line 739, in __new__
    instance._parent = cls.get_context(error_if_none=False)
  File "/Users/fb90/anaconda3/envs/pymc3/lib/python3.7/site-packages/pymc3/model.py", line 213, in get_context
    candidate = cls.get_contexts()[idx] # type: Optional[T]
  File "/Users/fb90/anaconda3/envs/pymc3/lib/python3.7/site-packages/pymc3/model.py", line 234, in get_contexts
    context_class = cls.context_class
  File "/Users/fb90/anaconda3/envs/pymc3/lib/python3.7/site-packages/pymc3/model.py", line 260, in context_class
    cls._context_class = resolve_type(cls._context_class)
  File "/Users/fb90/anaconda3/envs/pymc3/lib/python3.7/site-packages/pymc3/model.py", line 254, in resolve_type
    c = getattr(modules[cls.__module__], c)
AttributeError: module '__main__' has no attribute 'Model'
```

## Versions and main components

* PyMC3 Version: 3.8
* Theano Version: 1.0.4
* Python Version: 3.7
* Operating system: MacOS
* How did you install PyMC3: conda

**Comment by ac-optimus** [comment]
Hi, 
Below code does not throw the error :
```
from pymc3 import Model, Normal

class CustomModel(Model):
    def __init__(self):
        super().__init__(self)
        self.x = Normal("x", 0.0, 1.0)

model = CustomModel()


```
Check if this ease your work a little bit.
Thanks!

**Comment by lucianopaz** [comment]
Thanks for reporting @fbartolic. @rpgoldman, could you take a look at this? It seems that this bug happens in the context manager metaclass. We didn't test against `Model` subclasses so it didn't pop up when we refactorred it.

**Comment by rpgoldman** [comment]
> Thanks for reporting @fbartolic. @rpgoldman, could you take a look at this? It seems that this bug happens in the context manager metaclass. We didn't test against `Model` subclasses so it didn't pop up when we refactorred it.

I'll have a look at it ASAP, but won't be able to get to it for a few days: I'm frantically banging together a presentation for a meeting.  Maybe assign this to me?

**Comment by rpgoldman** [comment]
@fbartolic 

I was unable to replicate your error in a test.

I just created a test in this branch: https://github.com/rpgoldman/pymc3/tree/iss3727

```
def test_subclassing():
    """Test for issue 3727"""
    class CustomModel(pm.Model):
        def __init__(self):
            super().__init__()
            self.x = pm.Normal("x", 0.0, 1.0)

    model = CustomModel()
```

When I run it, it runs to completion with no error.

*However* when I run your code at the top level, I *do* see the error.  So this looks like a scoping problem.  I will try to fix it.  If anyone knows how to test something like this that only crops up at top level, I would love to know.

**Comment by rpgoldman** [comment]
Ah, I see the problem. It's this line:

```
class Model(Factor, WithMemoization, metaclass=ContextMeta, context_class='Model'):
```

I put that string in there, because the self-reference cannot be de-referenced until the class is created.  I'll have to figure out a better solution.

**Comment by rpgoldman** [comment]
Somehow this didn't get closed when #3856 was merged.  Closing.
