### PR TITLE
WIP Travis sphinx

### PR DESCRIPTION
**Pull request by twiecki**

### CODE REVIEW

**Comment by junpenglao** [comment]
Is this ready?

**Comment by twiecki** [comment]
No, haven't had time yet to investigate further why the development requirements don't get installed.

**Comment by junpenglao** [comment]
I see. So the website is currently updated manually?

**Comment by twiecki** [comment]
Correct.

**Comment by twiecki** [comment]
`Extension error:
Could not import recommonmark.parser (needed for source parser) (exception: cannot import name DocParser)` I have no idea why this happens, recommonmark should be installed.

**Comment by ColCarroll** [comment]
Hmm...  I see `Successfully installed CommonMark-0.7.4 PyYAML-3.12 argh-0.26.2 future-0.16.0 livereload-2.5.1 nbsphinx-0.2.14 pathtools-0.1.2 port-for-0.3.1 pycodestyle-2.3.1 pyflakes-1.6.0 recommonmark-0.4.0 sphinx-autobuild-0.7.1 watchdog-0.8.3`

However, trying locally, it doesn't work with `recommonmark-0.4.0`.  This is strange, but it works when I then `pip install --upgrade recommonmark`, which gives me the same version of `recommonmark`, but a lower version of `CommonMark`.  

I think a fix is to change the requirement to `CommonMark==0.5.4`.

**Comment by twiecki** [comment]
That fixed it @ColCarroll, thanks!

Rest continues to confuse me:
```
Warning, treated as error:
/home/travis/build/pymc-devs/pymc3/pymc3/distributions/multivariate.py:docstring of pymc3.distributions.multivariate.LKJCholeskyCov:57: (SEVERE/4) Unexpected section title.
Implementation
--------------
```

https://github.com/pymc-devs/pymc3/blob/master/pymc3/distributions/multivariate.py#L848

Anyone and idea what's wrong there?

**Comment by ColCarroll** [comment]
Reopening, assuming mistake!

**Comment by ColCarroll** [comment]
Sigh... that was a bad rebase -- will revert.  I think it builds now, though!

**Comment by ColCarroll** [comment]
Sorry, @twiecki
