### ISSUE TITLE
Theano breaks on new numpy

### ISSUE THREAD

**Issue by ColCarroll** [pymc-devs/pymc#3340]
Running `pip install pymc3` in a fresh environment today installs `numpy==1.16.0`, which throws an error (via `theano`) for pretty much any input. We should pin numpy to below 1.16 for now, until we can get a fix into theano.

Here's one reproducible example along with the traceback:

```python
with pm.Model():
    pm.Normal('x')
    pm.sample()
```

```pythontb
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 41, in __new__
    dist = cls.dist(*args, **kwargs)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/pymc3/distributions/distribution.py", line 52, in dist
    dist.__init__(*args, **kwargs)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/pymc3/distributions/continuous.py", line 432, in __init__
    self.variance = 1. / self.tau
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/tensor/var.py", line 203, in __rtruediv__
    return theano.tensor.basic.true_div(other, self)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/op.py", line 670, in __call__
    no_recycling=[])
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1609, in cthunk_factory
    key = self.cmodule_key()
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1300, in cmodule_key
    c_compiler=self.c_compiler(),
  File "/Users/rustrulz/miniconda3/envs/pymc3_bug3.6/lib/python3.6/site-packages/theano/gof/cc.py", line 1379, in cmodule_key_
    np.core.multiarray._get_ndarray_c_version())
AttributeError: module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'
```

**Comment by ColCarroll** [comment]
Oh hai -- looks like it is fixed on theano master: https://github.com/Theano/Theano/pull/6671

**Comment by nouiz** [comment]
We just released Theano 1.0.4 that added support for numpy 1.16 on the CPU. We didn't test on the GPU.

**Comment by twiecki** [comment]
Seems like we should pin to `theano >= 1.0.4`

**Comment by poiuwn** [comment]
@ColCarroll I am a newbie to PyMC and Bayesian. I installed Anaconda 3 and PyMC3 yesterday [Apr 13, 2019], but when I try to run code similar to your code snippet, I also have this error:
AttributeError: module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'

I believe you people are talking about a workaround. But when you say pin to higher theano, what does that mean? And what should I do exactly? I also went to the URL of Pin to higher theano #3342 but I did not find out what to do.
Here is my environment:
np.__version__
Out[234]: '1.16.2'
pm.__version__
Out[235]: '3.6'

thank you for your attention

**Comment by ericmjl** [comment]
@poiuwn, to pin to a higher version of theano means to ensure that you are using at least theano version >=1.0.4. 

You can do this in your environment.yml file (if you are using conda environments), or your requirements.txt file (if you are using a virtual env (`venv`)). I would refer to their respective documentation to specify how to pin a dependency to a particular version.

**Comment by poiuwn** [comment]
@ericmjl Thanks so much for your prompt reply. I am using Anaconda 3. 
I downloaded environment.yml following the instruction at https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file . The downloaded file has an entry that reads:   - theano=1.0.3=py37_0.
Do I need to do something about it?
The downloaded file is attached for your convenience. 

[environmentExported.zip](https://github.com/pymc-devs/pymc3/files/3080882/environmentExported.zip)

**Comment by ericmjl** [comment]
> Do I need to do something about it?

@poiuwn yes, I would change that line to:

```
- theano>=1.0.4
```

You can remove the `py37_0`.

**Comment by poiuwn** [comment]
@ericmjl Thanks for your reply. Indeed I have never dealth with environment.yml file, so I find it easier to upgrade the Theano to 1.0.4, which i did by pip install --upgrade theano. After that the error disappears.

Thanks again for your help.

**Comment by reemlores** [comment]
Hi everyone
I got the same error :" AttributeError: module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'" 
even after upgrading Theano to 1.0.4. 
Python version 3.7
numpy version 1.16.2

**Comment by ericmjl** [comment]
@reemlores can you paste here the output of the following?

```
$ which pip
$ which python
$ conda env list 
```

My first hunch is environment mismatch.

**Comment by reemlores** [comment]
thank you for your quick response, and sorry for being late. 
`pip 19.0.3`
`Python 3.7.3`
`conda env list
# conda environments:
#
base                  *  C:\Users\Stars\Anaconda3
Tweet2vec_T              C:\Users\Stars\Anaconda3\envs\Tweet2vec_T
python                   C:\Users\Stars\Anaconda3\envs\python
reem                     C:\Users\Stars\Anaconda3\envs\reem
`

**Comment by ericmjl** [comment]
Ok, so it looks like you've got a Windows installation. I'll be out of my depth here, as I've only ever used *nix systems (macOS/Linux) since 2006. The most generic help I can give here is to check that you've upgraded the correct version of theano that lives in the correct conda environment. Other than that, I'm going to have to defer to others on the team who have more experience with Windows.

**Comment by reemlores** [comment]
By listing the packages version in the (base * C:\Users\Stars\Anaconda3) environment: 
theano                    1.0.4+unknown            pypi_0    pypi  
and thank you for your suggestion

**Comment by lucianopaz** [comment]
I had a similar [problem](https://discourse.pymc.io/t/error-in-basic-model-due-to-trigonometric-functions-using-math-library/2825/11?u=lucianopaz) and I think that I solved it by uninstalling and reinstalling numpy.

**Comment by ColCarroll** [comment]
Somehow this rehappened to me, too, and I had to actually uninstall numpy multiple times! I guess conda and pip put them in different places.

**Comment by lucianopaz** [comment]
It's weird that theano is not well encapsulated in the conda environment though. It seems to look for system wide installations of some packages and libraries, but that may mess up things. Maybe, that's behind the strange errors we sometimes get with multiprocessing on windows?

**Comment by reemlores** [comment]
Hi. 
After several tries of installing and removing numpy package, it works.

**Comment by ericmjl** [comment]
It looks like that's the official solution!

"Install and remove NumPy, several times."

Jokes aside, I'm glad you were able to resolve it, @reemlores :smile:

**Comment by EzeCyviz** [comment]
Could somebody help me to find the root cause of this error:

AttributeError: ('The following error happened while compiling the node', Elemwise{mul,no_inplace}(TensorConstant{20}, <TensorType(int64, scalar)>), '\n', "'module' object has no attribute '_get_ndarray_c_version'")

**Comment by ericmjl** [comment]
Also looks like a NumPy issue, which I recognize from the `_get_ndarray_c_version`. 

Try re-creating your environment using [an environment.yml file](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file).

**Comment by nouiz** [comment]
The last release of Theano 1.0.4 should have this fixed. Can you specify
the version of Theano and NumPy you are using?
Downgrading NumPy to 1.15.* should fix this in all cases. But as a few
people are using the lastest Theano version have this problem, I would like
to see how to fix this.

$ which pip
$ which python
$ conda env list

**Comment by EzeCyviz** [comment]
This is recent bug as I made some changes. Please could check and assist me
please

Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 15:49:40) [MSC v.1500
32 bit (Intel)]
Type "copyright", "credits" or "license" for more information.
IPython 5.8.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
loading data
Traceback (most recent call last):
  File "<ipython-input-1-2dbee3f21a76>", line 1, in <module>
    runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 786, in runfile
    execfile(filename, namespace)
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 244, in
<module>
    TrainDNNModel()
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 172, in
TrainDNNModel
    datasets = DNN.LoadData(dataPath)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 59, in
LoadData
    train_set_x, train_set_y = shared_dataset(train_set)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 54, in
shared_dataset
    shared_x =
theano.shared(numpy.asarray(data_x,dtype=theano.config.floatX),
borrow=borrow)
  File "C:\Users\Sunday\Anaconda2\lib\site-packages\numpy\core\numeric.py",
line 538, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError


runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
Reloaded modules: lazylinker_ext.lazylinker_ext, lazylinker_ext
loading data
Traceback (most recent call last):
  File "<ipython-input-2-2dbee3f21a76>", line 1, in <module>
    runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 786, in runfile
    execfile(filename, namespace)
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 244, in
<module>
    TrainDNNModel()
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 172, in
TrainDNNModel
    datasets = DNN.LoadData(dataPath)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 49, in
LoadData
    train_set, valid_set, test_set  = cPickle.load(f)
  File "C:\Users\Sunday\Anaconda2\lib\gzip.py", line 267, in read
    self._read(readsize)
  File "C:\Users\Sunday\Anaconda2\lib\gzip.py", line 319, in _read
    self._add_read_data( uncompress )
  File "C:\Users\Sunday\Anaconda2\lib\gzip.py", line 337, in _add_read_data
    self.extrabuf = self.extrabuf[offset:] + data
MemoryError


runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
loading data
Traceback (most recent call last):
  File "<ipython-input-3-2dbee3f21a76>", line 1, in <module>
    runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 786, in runfile
    execfile(filename, namespace)
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 244, in
<module>
    TrainDNNModel()
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 172, in
TrainDNNModel
    datasets = DNN.LoadData(dataPath)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 59, in
LoadData
    train_set_x, train_set_y = shared_dataset(train_set)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 54, in
shared_dataset
    shared_x =
theano.shared(numpy.asarray(data_x,dtype=theano.config.floatX),
borrow=borrow)
  File "C:\Users\Sunday\Anaconda2\lib\site-packages\numpy\core\numeric.py",
line 538, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError


runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
loading data
Traceback (most recent call last):
  File "<ipython-input-4-2dbee3f21a76>", line 1, in <module>
    runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 786, in runfile
    execfile(filename, namespace)
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 244, in
<module>
    TrainDNNModel()
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 172, in
TrainDNNModel
    datasets = DNN.LoadData(dataPath)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 49, in
LoadData
    train_set, valid_set, test_set  = cPickle.load(f)
  File "C:\Users\Sunday\Anaconda2\lib\gzip.py", line 267, in read
    self._read(readsize)
  File "C:\Users\Sunday\Anaconda2\lib\gzip.py", line 319, in _read
    self._add_read_data( uncompress )
  File "C:\Users\Sunday\Anaconda2\lib\gzip.py", line 337, in _add_read_data
    self.extrabuf = self.extrabuf[offset:] + data
MemoryError


runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
loading data
Traceback (most recent call last):
  File "<ipython-input-5-2dbee3f21a76>", line 1, in <module>
    runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 786, in runfile
    execfile(filename, namespace)
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 244, in
<module>
    TrainDNNModel()
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 172, in
TrainDNNModel
    datasets = DNN.LoadData(dataPath)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 59, in
LoadData
    train_set_x, train_set_y = shared_dataset(train_set)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 54, in
shared_dataset
    shared_x =
theano.shared(numpy.asarray(data_x,dtype=theano.config.floatX),
borrow=borrow)
  File "C:\Users\Sunday\Anaconda2\lib\site-packages\numpy\core\numeric.py",
line 538, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError


runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
loading data
Traceback (most recent call last):
  File "<ipython-input-6-2dbee3f21a76>", line 1, in <module>
    runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 786, in runfile
    execfile(filename, namespace)
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 244, in
<module>
    TrainDNNModel()
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 172, in
TrainDNNModel
    datasets = DNN.LoadData(dataPath)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 49, in
LoadData
    train_set, valid_set, test_set  = cPickle.load(f)
  File "C:\Users\Sunday\Anaconda2\lib\gzip.py", line 267, in read
    self._read(readsize)
  File "C:\Users\Sunday\Anaconda2\lib\gzip.py", line 319, in _read
    self._add_read_data( uncompress )
  File "C:\Users\Sunday\Anaconda2\lib\gzip.py", line 337, in _add_read_data
    self.extrabuf = self.extrabuf[offset:] + data
MemoryError


runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
loading data
Traceback (most recent call last):
  File "<ipython-input-7-2dbee3f21a76>", line 1, in <module>
    runfile('C:/Users/Sunday/.spyder/DeepLearningNetwork.py',
wdir='C:/Users/Sunday/.spyder')
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 786, in runfile
    execfile(filename, namespace)
  File
"C:\Users\Sunday\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py",
line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 244, in
<module>
    TrainDNNModel()
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 172, in
TrainDNNModel
    datasets = DNN.LoadData(dataPath)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 59, in
LoadData
    train_set_x, train_set_y = shared_dataset(train_set)
  File "C:/Users/Sunday/.spyder/DeepLearningNetwork.py", line 54, in
shared_dataset
    shared_x =
theano.shared(numpy.asarray(data_x,dtype=theano.config.floatX),
borrow=borrow)
  File "C:\Users\Sunday\Anaconda2\lib\site-packages\numpy\core\numeric.py",
line 538, in asarray
    return array(a, dtype, copy=False, order=order)
MemoryError

**Comment by ericmjl** [comment]
`MemoryError` indicates that something, maybe your arrays, don't fit in memory.

What is the shape of `data_x`?

**Comment by EzeCyviz** [comment]
It is an array used to store MNIST handwritten digital data, which are rasterized. The shape is one dimensional

This is another detail about the bug 
  Anaconda2\lib\site-packages\numpy\core\numeric.py", line 538, in asarray
    return array(a, dtype, copy=False, order=order)

MemoryError

**Comment by nouiz** [comment]
This look likes you are missing memory on the computer. Do you have other
process running that are taking memory?
Your change probably raised the memory usage requirement.

**Comment by kreegah** [comment]
Just installed the latest Anaconda3 release. It has got Theano 1.0.3 module. Trying to run "import theano" gets me the dreaded  "module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'".

Trying to upgrade theano with "conda upgrade theano" just gets me # All requested packages already installed.

So back to square 1. Any suggestions?

**Comment by nouiz** [comment]
Try to install Theano 1.0.4 not included by default in anaconda. From
memory, this would be installed by:

conda install theano==1.0.4 -c theano

**Comment by edterrell** [comment]
I had the same error :
" AttributeError: module 'numpy.core.multiarray' has no attribute '_get_ndarray_c_version'"
but was able to solve it after upgrading Theano to 1.0.4.  (via conda) and updating Numpy as well.

**Comment by eric-wieser** [comment]
This is a numpy bug, and is fixed by numpy/numpy#13876.

Please do report these things upstream, if they're not reported we can't fix them.

**Comment by twiecki** [comment]
@eric-wieser Thanks, it actually hadn't occurred to me that this could be a numpy bug (numpy has bugs? ;)).

**Comment by jpclemente** [comment]
For all of you that are trying to fix the problem by upgrading theano, just remember to activate your environment (that with the 1.0.3 version) before execute pip install --upgrade theano. Otherwise you'll be just upgrading the version in your conda base environment.
