### ISSUE TITLE
aesara 2.0.8 - ImportError: cannot import name 'sigmoid' from 'aesara.tensor.nnet'

### ISSUE THREAD

**Issue by andrewjgray1001** [pymc-devs/pymc#4690]
## pymc3/math cannot resolve sigmoid using aesara 2.0.8

I have just rebuilt a docker image which uses pymc3 v 3.11.1, this works fine with aesara 2.0.7, but fails with aesara 2.0.8

to fix this for the moment I have regressed to aesara 2.0.7

**traceback.**
```python
~/project/f_probabilisticregression.py in <module>
      1 import pandas as pd
      2 
----> 3 import pymc3 as pm
      4 import arviz as az
      5 

~/pymc3/__init__.py in <module>
     39 __set_compiler_flags()
     40 
---> 41 from pymc3 import gp, ode, sampling
     42 from pymc3.aesaraf import *
     43 from pymc3.backends import load_trace, save_trace

~/pymc3/gp/__init__.py in <module>
     14 
     15 from pymc3.gp import cov, mean, util
---> 16 from pymc3.gp.gp import TP, Latent, LatentKron, Marginal, MarginalKron, MarginalSparse

~/pymc3/gp/gp.py in <module>
     23 import pymc3 as pm
     24 
---> 25 from pymc3.distributions import draw_values
     26 from pymc3.gp.cov import Constant, Covariance
     27 from pymc3.gp.mean import Zero

~/pymc3/distributions/__init__.py in <module>
     13 #   limitations under the License.
     14 
---> 15 from pymc3.distributions import shape_utils, timeseries, transforms
     16 from pymc3.distributions.bart import BART
     17 from pymc3.distributions.bound import Bound

~/pymc3/distributions/timeseries.py in <module>
     19 from scipy import stats
     20 
---> 21 from pymc3.distributions import distribution, multivariate
     22 from pymc3.distributions.continuous import Flat, Normal, get_tau_sigma
     23 from pymc3.distributions.shape_utils import to_tuple

~/pymc3/distributions/distribution.py in <module>
     45     to_tuple,
     46 )
---> 47 from pymc3.model import (
     48     ContextMeta,
     49     FreeRV,

~/pymc3/model.py in <module>
     41 from pymc3.blocking import ArrayOrdering, DictToArrayBijection
     42 from pymc3.exceptions import ImputationWarning
---> 43 from pymc3.math import flatten_list
     44 from pymc3.util import WithMemoization, get_transformed_name, get_var_name, hash_key
     45 from pymc3.vartypes import continuous_types, discrete_types, isgenerator, typefilter

~/pymc3/math.py in <module>
     79 
     80 from aesara.tensor.nlinalg import det, matrix_dot, matrix_inverse, trace
---> 81 from aesara.tensor.nnet import sigmoid
     82 from scipy.linalg import block_diag as scipy_block_diag
     83 

ImportError: cannot import name 'sigmoid' from 'aesara.tensor.nnet' (/opt/conda/lib/python3.8/site-packages/aesara/tensor/nnet/__init__.py)
```

## Versions and main components

* PyMC3 Version: 3.11.1
* Aesara Version: 2.0.7/8
* Python Version: 3.8
* Operating system: docker (desktop)
* How did you install PyMC3: conda, some additional libs using pip

**Comment by ricardoV94** [comment]
Pymc3 3.11 should be using Theano-pymc and not aesara

**Comment by andrewjgray1001** [comment]
ok, thank you - I will change it

**Comment by andrewjgray1001** [comment]
ok, thank you - I will change it

**Comment by KOLANICH** [comment]
I absolutely don't understand anything.
1. The bug is still present in `master` of this repo.
2. and the source code of Theano-PyMC from pypi is almost identical to the one of aesara - it just has the word `aesara` replaced with the word `theano`

**Comment by ricardoV94** [comment]
The `master` branch of this repo is currently in a non-functional limbo state. We will soon merge the branch `V4` into `master` which will then be working with `aesara >= 2.0.8` (`aesara` has changed quite a lot from `theano`). Even after that `master` will still be in a pre-alpha state with missing functionality.

Stable source-code can currently be found in the `V3` branch of this repo, which depends on `theano-pymc` and which is basically a frozen fork of `theano`.

**Comment by brandonwillard** [comment]
We could add a deprecation stub/alias to Aesara and make the complete removal after `master` is updated.  That's how we need to start handling user-facing changes anyway.

**Comment by KOLANICH** [comment]
Thanks for the info. Of course compatibility should be preserved, since `aesara` claims to be a continuation of `theano`.

**Comment by brandonwillard** [comment]
> Thanks for the info. Of course compatibility should be preserved, since `aesara` claims to be a continuation of `theano`.

Preserving the Theano interface isn't one of Aesara's goals.  Aesara is definitely its own thing and will likely diverge significantly from Theano over time.  

The one thing it does maintain between the two is basic NumPy compatibility.  Just like Theano, Aesara tries to keep a basic level of parity with the NumPy user interface (e.g. the same function names, arguments, results, etc.)  Without that, there would be even more overhead to using Aesara, because people wouldn't be able to relate it to something they likely already know&mdash;like NumPy.

The kind of compatibility I mentioned previously is specific to Aesara itself (i.e. between versions) and its deprecation policy.

**Comment by JaimeArboleda** [comment]
Hello. I am having the same issue. I have tried using the official docker image: 
https://hub.docker.com/r/pymc/pymc3
And when importing it gives me the same error. What's the solution, then? 
Thanks in advance!

I am trying to run this notebook: 
https://github.com/pymc-devs/resources/blob/master/Rethinking_2/Chp_02.ipynb

And neither locally nor using docker I have been able to do it.
